import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv("player_data.csv")  
print("\n---Dataset Info ---")
print(df.info())
print("\n--- Missing Values ---")
print(df.isnull().sum())
print("\n--- Summary Statistics ---")
print(df.describe())
sns.set(style="whitegrid", palette="muted")
plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap of Numeric Features")
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 5))
sns.histplot(df["market_value"], kde=True, bins=30)
plt.title("Distribution of Player Market Value")
plt.xlabel("Market Value (in Millions)")
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 5))
sns.boxplot(data=df, x="position_cat", y="market_value")
plt.title("Market Value by Position Category")
plt.xlabel("Position Category (1-Attack, 2-Mid, 3-Def, 4-GK)")
plt.ylabel("Market Value")
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 5))
sns.scatterplot(data=df, x="age", y="market_value", hue="position_cat", palette="tab10")
plt.title("Market Value vs Age Colored by Position")
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 5))
sns.scatterplot(data=df, x="page_views", y="market_value", hue="big_club")
plt.title("Market Value vs Wikipedia Page Views (Big Club vs Non-Big Club)")
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 5))
sns.scatterplot(data=df, x="fpl_sel", y="market_value", hue="position_cat")
plt.title("FPL Selection % vs Market Value")
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 5))
sns.boxplot(data=df, x="region", y="market_value")
plt.title("Market Value by Region")
plt.xlabel("Region (1-England, 2-EU, 3-Americas, 4-Rest)")
plt.tight_layout()
plt.show()
